module.exports = {
    addTrail: {
        'Allow Edit without Parent Edit Permissions': 'set to "No"',
        'Allow manual entry of External ID/Source': 'set to "No"',
        'Allow records to be locked': 'set to "No"',
        'Collect': 'changed from "One Record" to "Many Records"',
        'Create Qiagram Datasource': 'set to "Yes"',
        'Display Column Number': 'set to "2"',
        'Display For New Records': 'set to "No"',
        'Make Available in Data Entry': 'set to "Yes"',
        'Make Available in Search': 'set to "Yes"',
        'Name': 'set to "Test Automation Form"',
        'Show Attachments': 'set to "No"',
        'Added Fields': '(ID=',
        'Add New Values To List': 'set to "Yes"',
        'Contains PHI': 'set to "No"',
        'Decimal Precision': 'set to "10"',
        'Default to Current Date/Time': 'set to "No"',
        'External ID': 'set to "Field1"',
        'Is Required': 'set to "Yes"',
        'Is Title': 'set to "No"',
        'Label': 'set to "Lable1"',
        'Location': 'set to "In-line"',
        'Maximum': 'set to "250"',
        'Name': 'set to "Field1"',
        'Show Help Text': 'set to "as tooltip"',
        'Type': 'set to "Text"',
        'Added Fields': '(ID=',
        'Add New Values To List': 'set to "Yes"',
        'Contains PHI': 'set to "No"',
        'Decimal Precision': 'set to "10"',
        'Default to Current Date/Time': 'set to "No"',
        'External ID': 'set to "Field2"',
        'Is Required': 'set to "Yes"',
        'Is Title': 'set to "No"',
        'Label': 'set to "Lable2"',
        'Location': 'set to "In-line"',
        'Name': 'set to "Field2"',
        'Show Help Text': 'set to "as tooltip"',
        'Type': 'set to "Integer"',
 },
    updateTrail: {
        'Updated Fields': '(ID=',
        'Name': 'changed from "Field1" to "Field1 Updated"'
 }

}
 